[Writable]
LogLevel = 'INFO'

[Service]
HealthCheckInterval = '10s'
Host = ''
Port = 49986
ServerBindAddr = ''  # blank value defaults to Service.Host value
StartupMsg = 'device rest started'
# MaxRequestSize limit the request body size in byte of put command
MaxRequestSize = 0 # value 0 unlimit the request size.
RequestTimeout = '5s'

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Clients]
  [Clients.core-data]
  Protocol = 'http'
  Host = 'localhost'
  Port = 59880

  [Clients.core-metadata]
  Protocol = 'http'
  Host = 'localhost'
  Port = 59881

[Device]
DataTransform = true
MaxCmdOps = 128
MaxCmdValueLen = 256
ProfilesDir = './res/profiles'
DevicesDir = './res/devices'
UpdateLastConnected = true
Labels = []
EnableAsyncReadings = true
AsyncBufferSize = 16
UseMessageBus = false

# Driver configs
# [Driver]
